---
name: mariadb-solo
director_uuid: DIRECTOR_UUID
releases:
- name: mariadb
  version: latest
compilation:
  workers: 3
  network: mariadb-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random
update:
  canaries: 1
  max_in_flight: 4
  canary_watch_time: 10000-60000
  update_watch_time: 10000-60000
resource_pools:
- name: common
  network: mariadb-network
  size: 1
  stemcell:
    name: bosh-stemcell
    version: latest
  cloud_properties:
    name: random
networks:
- name: mariadb-network
  subnets:
<% (0..28).each_with_index do |i| %>
  - range: 10.244.0.<%= i*4 %>/30
    reserved:
      - 10.244.0.<%= i*4 + 1 %>
    static:
      - 10.244.0.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>
<% (29..61).each_with_index do |i| %>
  - range: 10.244.0.<%= i*4 %>/30
    reserved:
      - 10.244.0.<%= i*4 + 1 %>
    cloud_properties:
      name: random
<% end %>
<% (62..63).each_with_index do |i| %>
  - range: 10.244.0.<%= i*4 %>/30
    reserved:
      - 10.244.0.<%= i*4 + 1 %>
    static:
      - 10.244.0.<%= i*4 + 2 %>
    cloud_properties:
      name: random
<% end %>
jobs:
- name: mariadb
  template: mariadb
  instances: 1
  resource_pool: common
  networks:
  - name: mariadb-network
    static_ips:
    - 10.244.0.6
properties:
  mariadb: {}
